CREATE TABLE USUARIOS (
    ID INTEGER PRIMARY KEY,
    NOMBRE VARCHAR,
    CORREO VARCHAR,
    PASSWORD VARCHAR,
    DIRECCION VARCHAR,
    NUMERO_TLF INTEGER,
    imgPerfil_url VARCHAR
);

CREATE TABLE POSTS_PRODUCTOS (
    ID INTEGER PRIMARY KEY,
    ARTICULOS VARCHAR,
    DESCRIPCION TEXT,
    PRECIO INTEGER,
    DISPONIBILIDAD BOOLEAN,
    propietario_ID INTEGER,
    fecha_publicacion TIMESTAMP,
    img_url VARCHAR,
    FOREIGN KEY (propietario_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE FAVORITOS (
    ID INTEGER PRIMARY KEY,
    interesado_ID INTEGER,
    articulo_ID INTEGER,
    FOREIGN KEY (interesado_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (articulo_ID) REFERENCES POSTS_PRODUCTOS(ID)
);

SELECT 
    P.ID AS producto_id,
    P.ARTICULOS,
    P.DESCRIPCION,
    P.PRECIO,
    U.NOMBRE AS propietario
FROM POSTS_PRODUCTOS P
INNER JOIN USUARIOS U ON P.propietario_ID = U.ID;

SELECT 
    F.ID AS favorito_id,
    U.NOMBRE AS usuario_interesado,
    P.ARTICULOS AS producto_favorito
FROM FAVORITOS F
INNER JOIN USUARIOS U ON F.interesado_ID = U.ID
INNER JOIN POSTS_PRODUCTOS P ON F.articulo_ID = P.ID;
