CREATE TABLE USUARIOS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR,
    EMAIL VARCHAR,
    PASSWORD VARCHAR,
    DIRECCION VARCHAR,
    TELEFONO INTEGER,
    imgPerfil_url VARCHAR
);

CREATE TABLE POSTS_PRODUCTOS (
    ID SERIAL PRIMARY KEY,
    ARTICULOS VARCHAR,
    DESCRIPCION TEXT,
    PRECIO INTEGER,
    DISPONIBILIDAD BOOLEAN,
    propietario_ID INTEGER,
    fecha_publicacion TIMESTAMP,
    img_url VARCHAR,
    FOREIGN KEY (propietario_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE FAVORITOS (
    ID SERIAL PRIMARY KEY,
    interesado_ID INTEGER,
    articulo_ID INTEGER,
    FOREIGN KEY (interesado_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (articulo_ID) REFERENCES POSTS_PRODUCTOS(ID)
);

SELECT 
    P.ID AS producto_id,
    P.ARTICULOS,
    P.DESCRIPCION,
    P.PRECIO,
    U.NOMBRE AS propietario
FROM POSTS_PRODUCTOS P
INNER JOIN USUARIOS U ON P.propietario_ID = U.ID;

SELECT 
    F.ID AS favorito_id,
    U.NOMBRE AS usuario_interesado,
    P.ARTICULOS AS producto_favorito
FROM FAVORITOS F
INNER JOIN USUARIOS U ON F.interesado_ID = U.ID
INNER JOIN POSTS_PRODUCTOS P ON F.articulo_ID = P.ID;

SELECT * FROM USUARIOS;
SELECT * FROM POSTS_PRODUCTOS;
SELECT * FROM FAVORITOS;
ALTER TABLE POSTS_PRODUCTOS
ALTER COLUMN img_url TYPE TEXT;

UPDATE POSTS_PRODUCTOS
SET img_url = 'https://images.pexels.com/photos/3777622/pexels-photo-3777622.jpeg'
WHERE id = 2;